import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lora, Cinzel, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Inter — all structural UI chrome, SummaryEditor, NotesEditor (Inviolable #4)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Lora — ProseEditor only (Inviolable #4). italic variant needed for placeholder.
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

// Cinzel — wordmark only (Inviolable #3). Brand Identity v2.2 §3.2.
// 500 (Semibold) for STELA in the wordmark + S in AppIcon.
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["500", "600"],
});

// Cormorant Garamond italic — wordmark only (Inviolable #6 — added Phase 8.01).
// Brand Identity v2.2 §3.2: weight 300 (hero) and 400 (compact); italic only.
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400"],
  style: ["italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${lora.variable} ${cinzel.variable} ${cormorantGaramond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
